apiVersion: apps/v1
kind: Deployment 
metadata:
  name: app-name
spec:
  replicas: 1
  selector:
    matchLabels:
      # write labels that this deployment should control (it can be a combination of labels)
      app: second_app
  template: 
    metadata:
      labels:
        app: second_app
    spec:
      containers:
        # - is used for multiple containers
        - name: node-name
          image: kvitkovski/kub-first-app

